# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment. 
pipelines:
  branches:
    master:
      - step:
          name: Deploy Proyecto
          image: node:20.13.1
          caches:
            - node
          script:
            - echo "Setting up SSH"
            - mkdir -p ~/.ssh
            - echo "$SERVER_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - ssh-keyscan -p 2222 $SERVER_HOST >> ~/.ssh/known_hosts
            - echo "Deploying via SSH"
            - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST 'bash -s' < /home/image-uploader.reffcovarrubias.com/api/image-uploader-backend/deploy.sh
          services:
            - docker

definitions:
  caches:
    node: ~/.npm

definitions:
  services:
    docker:
      memory: 1024

